In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
from sklearn.datasets import load_boston
dataset =load_boston() # In this dataset we have to predict the price of the house based on various features
dataset # The data is in the form of an array

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [3]:
df = pd.DataFrame(dataset.data) # Using pandas, converting the data in array form to a dataframe
df.head()

0     1     2    3      4      5     6       7    8      9     10  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   

       11    12  
0  396.90  4.98  
1  396.90  9.14  
2  392.83  4.03  
3  394.63  2.94  
4  396.90  5.33

In [4]:
df.columns=dataset.feature_names
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [5]:
df["Price"]=dataset.target
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  Price  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [6]:
X = df.iloc[ : , :-1] 
y = df.iloc[ : , -1]

### Linear Regression

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score # Used to do cross validation
lr = LinearRegression()

In [8]:
mse=cross_val_score(lr,X,y,scoring='neg_mean_squared_error',cv=5) # cv = 5 --> Conducting 5 experiments, we get 5 values in the form of list
# The value must be more nearer to 0. More the value nearer to 0, model performs well
mse 

array([-12.46030057, -26.04862111, -33.07413798, -80.76237112,
       -33.31360656])

In [9]:
mean_mse=np.mean(mse)
print(mean_mse)

-37.13180746769901


### Ridge Regression

In [10]:
from sklearn.linear_model import Ridge
ridge=Ridge()

In [11]:
# In ridge regression we have to find out the value of lambda, it can be found out by cross validation 
from sklearn.model_selection import GridSearchCV # To find out lambda by cross validation
parameters={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20,30,35,40,45,50,55,100,150,200,1000]} # alpha value must be greater than 0.

In [12]:
ridge_regression=GridSearchCV(ridge,parameters,scoring='neg_mean_squared_error',cv=5) # We can find out which alpha suits for this problem statement
ridge_regression.fit(X,y)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20, 30, 35, 40, 45, 50, 55, 100, 150, 200,
                                   1000]},
             scoring='neg_mean_squared_error')

In [13]:
ridge_regression.best_params_

{'alpha': 150}

In [14]:
ridge_regression.best_score_ # Gives the average value

-29.75361723414273

### Lasso Regression: Usually Lasso performs well when we have many features

In [15]:
# In Lasso regression we almost perform the same thing
from sklearn.linear_model import Lasso
lasso=Lasso()

In [16]:
from sklearn.model_selection import GridSearchCV
parameters={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20,30,35,40,45,50,55,100,150,200,1000]}
lasso_regression=GridSearchCV(lasso,parameters,scoring='neg_mean_squared_error',cv=5)

In [17]:
lasso_regression.fit(X,y)
lasso_regression.best_params_

{'alpha': 1}

In [18]:
lasso_regression.best_score_ # Gives the average value of the scores obtained from best obtained parameters

-35.53158022069486

### Checking the accuracy

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.25 , random_state = 0 )

In [20]:
prediction_ridge=ridge_regression.predict(X_test)
prediction_ridge

array([23.87067189, 25.14230084, 27.54298269, 14.48876057, 19.6101164 ,
       21.57757633, 21.41737711, 23.50292958, 20.61427089, 19.54764058,
        6.57333952, 14.05412651, 18.52718864,  7.60256759, 36.55093269,
       31.24647314, 22.31425838, 35.04225713, 30.89541099, 24.40414543,
       25.45147454, 24.56827297, 20.1858374 , 30.04760931, 22.88556631,
       14.99279067, 18.81765769, 21.68482648, 32.78262625, 19.7606236 ,
       18.13619394, 20.03927549, 20.78458978, 23.71297826, 28.95646668,
       20.78711955, 11.03899199, 25.30759349, 16.26578226, 13.57328925,
       24.97792985, 20.37330839, 21.59861668, 16.27072541, 22.64439635,
       25.07956342, 18.64582893, 23.89621241, 12.30268754, 23.87428396,
       21.5926983 , 17.41481994, 24.90379049, 28.11562425, 13.6984305 ,
       21.35265114, 20.67419442, 15.6743815 , 16.00670584, 19.51792654,
       19.33145224, 21.89075698, 31.67767597, 31.53085956, 18.3925527 ,
       31.79956468, 19.30829785, 18.37259385, 16.77191646, 22.87

In [21]:
accuracy_score_1 = ridge_regression.score(X_test , y_test)
accuracy_score_1

-31.3626091859214

In [22]:
prediction_lasso=lasso_regression.predict(X_test)
prediction_lasso

array([23.74549008, 25.05669894, 27.30699681, 15.26474466, 20.28388223,
       22.75172373, 21.45598059, 24.23856649, 21.11819135, 19.95909495,
        8.98313974, 13.30218316, 17.99925624,  8.39272295, 35.35448484,
       30.78862119, 22.38396018, 34.3159854 , 29.8521009 , 24.63915134,
       25.7851669 , 25.20997813, 20.07312698, 29.34704456, 23.54801802,
       17.49320154, 19.76581421, 22.02254005, 31.35043449, 19.53061141,
       17.86731915, 20.03959005, 22.70589322, 24.27507125, 28.3321545 ,
       20.26286175, 10.68729818, 24.94704305, 15.84336797, 12.8254677 ,
       25.41186454, 20.63647768, 22.05355817, 16.77749717, 23.30629191,
       25.77681736, 19.84379805, 23.32853181, 12.22570134, 23.7054699 ,
       21.09270778, 16.76593695, 24.7895207 , 27.77843148, 15.02615536,
       21.29343807, 21.55732101, 17.59916216, 18.35971801, 19.53427781,
       21.69584327, 22.09466825, 30.77701755, 30.58126341, 18.59617266,
       31.00696923, 18.55257582, 18.71479862, 15.79040727, 22.86

In [23]:
accuracy_score_2 = lasso_regression.score(X_test , y_test)
accuracy_score_2

-34.369138225016755